// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clgotutymtcnyimeuueo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZ290dXR5bXRjbnlpbWV1dWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTkzODQsImV4cCI6MjA3MTUzNTM4NH0.7NvtI-2mNTppwRTFKKLG0vzweGlMAscBl5C2NSWYLIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});